### PR TITLE
PR for v.1.9.4

### LINKED ISSUE #200: Jupyter Error on rendering chart from_pandas when df has NaN values
**Describe the bug**

Issue to display a graph when rendered from pandas on jupyter context, where some values are NaN in the dataframe

**To Reproduce**

Run the following code on python jupyter environment, then switch the `None` data for some integer and it will yield the chart.
```python
import pandas as pd
import datetime as dt
import numpy as np
df = pd.DataFrame([
    {"ref_date": dt.date(2024, 1, 1), "data": 1},
    {"ref_date": dt.date(2024, 1, 2), "data": 5},
    {"ref_date": dt.date(2024, 1, 3), "data": 2},
    {"ref_date": dt.date(2024, 1, 4), "data": 4},
    {"ref_date": dt.date(2024, 1, 5), "data": None},
])

df['ref_date'] = pd.to_datetime(df['ref_date'])
df.set_index('ref_date', inplace=True)
df.index = (df.index.astype(np.int64) / 10**6).astype(np.int64)

from highcharts_core.chart import Chart
chart = Chart.from_pandas(
    df=df.reset_index(),
    series_type='line',
    property_map={
        'x': df.index.name,
        'y': df.columns.to_list()
    }
)

chart.options.x_axis = {
    'type': 'datetime'
}

chart.display()
```

I am getting the following error:

```bash
Something went wrong with the Highcharts.js script. It should have been automatically loaded, but it did not load for over 5 seconds. Check your internet connection, and then if the problem persists please reach out for support. (You can also check your browser's console log for more details.)

Detailed Error Message:
nan is not defined
```

**Expected behavior**

Attain a chart as:

image

**Your Environment:**
 - OS: WSL under ubuntu
  output of `lsb_release -a`:
  
  
image

 - Python Version: 3.12.3
 - Highcharts Core Version: 1.9.2 

**Additional context**

This is due to javascript not having `None` as `nan` , but rather `NaN` or `null`. I will be sending a PR shortly to fix this matter, as I have already found a solution

### PR DESCRIPTION
**Pull request by hcpchris**
* Closes #200 . Incorporated bugfix for handling `np.isnan()` operations that generate a `TypeError` when casting in safe-mode (the default). Thanks to @ThomasGL !

### CODE REVIEW

**Comment by ThomasGl** [comment]
Hey Chris,

Thank you so much for all your help in finishing up this PR! Also for merging it and editing the contributors to the project list. Prehaps there was something missing there, as I am not currently listed on the contributers section of the repo, not sure if I have to do some action on my side.

**Comment by ThomasGl** [comment]
Also I will check the fix on the safe casting type you made. I don't recall ever managing those on python before

**Comment by hcpchris** [comment]
@ThomasGl : Hmm - odd. It seems that Github is listing you as a contributor on the release (see [here](https://github.com/highcharts-for-python/highcharts-core/releases/tag/v.1.9.4) ) but for some reason not listing you on the overall Github contributors list. That seems decidedly strange to me. 

In any case, I've included you on the contributor list in the [docs](https://core-docs.highchartspython.com/en/latest/contributing.html#contributors) which get listed in a couple places there.

And as for the safe casting change, basically there were two types of value that were getting handled improperly by `np.isnan()`, specifically `Decimal` types and `None` which I was quite surprised to learn that `np.isnan()` errors out on when in "safe" casting mode. You can see the checking that takes place in the unit tests that I added: one test basically tries all of the scenarios that were present in the object that was erroring out in the unit tests (used to determine which scenarios were causing the problem), and the second test actually tests that now they work as expected in `get_js_literal()`.

**Comment by ThomasGl** [comment]
Hey Chris, I checked out the unit tests, they look great. It seems to me quite odd the safe casting type for the np.isnan(), I check on numpy lib if this behaviour is expected or some changes could be done in that matter.

As for the contributors mentions, I think there's some thing with how the PR was identified by guithub. I will try to contact them about it, in the meantime if you can check the git log and status of the repo there might be some indication there of what happend.

Thank you once more,
Thomas

**Pull request merged**
